spring.application.name=demo

# Fix the port to 3306 and add the database name at the end
spring.datasource.url=jdbc:mysql://localhost:3306/my_portfolio_project

# Add your MySQL credentials
spring.datasource.username=root
spring.datasource.password=example1234
spring.jpa.hibernate.ddl-auto=update
